os: osx
osx_image: xcode10.1

branches:
  only:
    - master

cache: ccache

jobs:
  - name: "RELEASE (Xcode 10.1)"
    env: BUILD_TYPE=Release

  - name: "DEBUG (Xcode 10.1)"
    env: BUILD_TYPE=Debug

language: cpp

script:
  # Install dependencies (this can take a looooong time...)
  - travis_wait 60 brew update
  - travis_wait 60 brew install ccache
  - travis_wait 60 brew install glew
  - travis_wait 60 brew install sdl2
  - travis_wait 60 brew install sdl2_image
  - travis_wait 60 brew install sdl2_mixer
  - travis_wait 60 brew install sdl2_ttf
  - travis_wait 60 brew install curl
  - travis_wait 60 brew install icu4c
  # icu4c cannot be forced
  - export ICU_ROOT="$(brew --prefix icu4c)"
  # Add ccache and gettext to the PATH variable
  - export PATH="/usr/local/opt/ccache/libexec:/usr/local/opt/gettext/bin:$PATH"
  # Compile
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE:STRING=$BUILD_TYPE -DOPTION_BUILD_TRANSLATIONS=ON -DOPTION_BUILD_WEBSITE_TOOLS=ON -DOPTION_ASAN="OFF" -DOPTION_BUILD_CODECHECK="OFF" -DCMAKE_EXE_LINKER_FLAGS="-L/usr/local/opt/gettext/lib -lintl" -DCMAKE_CXX_FLAGS="-I/usr/local/opt/gettext/include"
  - make -k -j3
